name: Build APK from HTML
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '请输入您要打包的项目的名称'
        required: true
      app_pkg_name:
        description: '请输入您要打包的项目的包名（示例：com.<Yourname>.<appname>）'
        required: true
        default: 'com.'
      file_path:
        description: '请输入html文件以项目根目录为基准的相对路径（以“/”作为路径分隔符）'
        required: true
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 你可以根据需要修改Node.js版本
      - name: Install Cordova
        run: |
          npm install -g cordova
      - name: Create Cordova project
        run: |
          cordova create ${{ github.event.inputs.app_name }} ${{ github.event.inputs.app_pkg_name }} ${{ github.event.inputs.app_name }}
          cd ${{ github.event.inputs.app_name }}
          cordova platform add android
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Create project structure for ${{ inputs.project_name }}"
          git push
          
