name: Build APK with Buildozer and Kivy

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '应用名称'
        required: true
        type: string
      package_name:
        description: '包名'
        required: true
        type: string
      domain:
        description: '域名'
        required: true
        type: string
      version:
        description: '版本号'
        required: true
        type: string
      file_path:
        description: '包含main.py的文件夹（仅限项目根目录算起往下一级）'
        required: true
        type: string

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libmtdev-dev libinput-dev libevdev-dev

    - name: 安装Kivy和Buildozer
      run: |
        pip3 install --upgrade pip setuptools
        pip3 install kivy buildozer
    - name: 切换到项目目录
      run: |
        cd ${{ github.event.inputs.file_path }}

    - name: 执行buildozer init
      run: buildozer init

    - name: 切换到上级目录
      run: cd ..

    - name: 使用python脚本修改buildozer.spec文件
      run: |
        python edit.py --app_name ${{ github.event.inputs.app_name }} --package_name ${{ github.event.inputs.package_name }} --domain ${{ github.event.inputs.domain }} --version ${{ github.event.inputs.version }}
      env:
        PROJECT_DIR: ${{ github.event.inputs.file_path }}

    - name: 切换回项目目录
      run: cd ${{ env.PROJECT_DIR }}

    - name: 打包APK
      run: buildozer -v android debug

    - name: 上传APK文件
      uses: actions/upload-artifact@v3
      with:
        name: my_app
        path: bin/*
